### ISSUE TITLE
missing collection gene_summaries ?

### ISSUE THREAD

**Issue by idiazblanco** [computer-conflict/genes_visual_analytics#2]
After successfully running
```
python ./db/datasets/datasets_downloader.py 
```
it fails when launching the app with
```
python main.py
```
It seems that `gene_summaries` file is missing. Below I show the full error trace
```
(.venv_manuel) (base) idiazblanco@Ordenador-portatil-de-Ignacio genes_visual_analytics-main % python main.py
/Users/idiazblanco/Downloads/genes_visual_analytics-main/.venv_manuel/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
 - UMAP time:
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
    10.218364238739014 s
 - Clustering time:
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
    1.1303420066833496 s
Traceback (most recent call last):
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/db/setup.py", line 115, in verify_semantic_info
    client.get_collection('gene_summaries')
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/.venv_manuel/lib/python3.11/site-packages/chromadb/api/client.py", line 218, in get_collection
    return self._server.get_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/.venv_manuel/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/.venv_manuel/lib/python3.11/site-packages/chromadb/api/segment.py", line 270, in get_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection gene_summaries does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/main.py", line 58, in <module>
    env_setup()
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/db/setup.py", line 168, in env_setup
    verify_semantic_info()
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/db/setup.py", line 117, in verify_semantic_info
    create_summary_collection('gene_summaries')
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/db/setup.py", line 101, in create_summary_collection
    df['color'] = get_collection_colors(labels)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/db/setup.py", line 84, in get_collection_colors
    return [colors[label] if label != -1 else 'rgba(128, 128, 128, 0.8)' for label in labels]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/idiazblanco/Downloads/genes_visual_analytics-main/db/setup.py", line 84, in <listcomp>
    return [colors[label] if label != -1 else 'rgba(128, 128, 128, 0.8)' for label in labels]
            ~~~~~~^^^^^^^
IndexError: tuple index out of range
^CException ignored in: <module 'threading' from '/Users/idiazblanco/anaconda3/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/Users/idiazblanco/anaconda3/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
```

**Comment by computer-conflict** [comment]
It seems that I missed including a palette in the setup. The fix is already in the main branch.
